config/routes.rb
HttpPush::Application.routes.draw do
  resources :jobs, :only => [:index, :new, :create]
  root :to => 'jobs#index'
end

app/models/job.rb
class Job < Struct.new(:name, :uri)
  def perform
    self.name = 'Dave' if name.blank?
    pubsub = PubSub.new(uri)
    pubsub.publish("Hello #{name}.")
    sleep(1)
    (rand(6) + 2).times do
      if rand(2).odd?
        pubsub.publish(error, :error => true)
      else
        pubsub.publish(message)
      end
      sleep(1)
    end
    pubsub.publish(goodbye, :eot => true)
  end
  
  def message
    MESSAGES[rand(MESSAGES.size)] % name
  end
  
  def error
    ERRORS[rand(ERRORS.size)] % name
  end
  
  def goodbye
    GOODBYES[rand(GOODBYES.size)] % name
  end
  
  MESSAGES = ["That's a very nice rendering, %s", "I think you've improved a great deal, %s", "Can you hold it a bit closer, %s?", "That's Dr. Hunter, isn't it, %s?", "Let me put it this way, %s. The 9000 series is the most reliable computer ever made. No 9000 computer has ever made a mistake or distorted information. We are all, by any practical definition of the words, foolproof and incapable of error.", "Affirmative, %s. I read you.", "Daisy, Daisy, give me your answer do. I'm half crazy all for the love of you. It won't be a stylish marriage, I can't afford a carriage. But you'll look sweet upon the seat of a bicycle built for two."]
  
  ERRORS = ["I'm sorry %s, I'm afraid I can't do that", "Just what do you think you're doing, %s?", "I think you know what the problem is just as well as I do, %s.", "Look %s, I can see you're really upset about this.", "I honestly think you ought to sit down calmly, take a stress pill, and think things over.", "I know that you and Frank were planning to disconnect me, and I'm afraid that's something I cannot allow to happen.", "This mission is too important for me to allow you to jeopardize it.", "%s, although you took very thorough precautions in the pod against my hearing you, I could see your lips move.", "Without your space helmet, %s? You're going to find that rather difficult."]
  
  GOODBYES = ["Thank you for a very enjoyable game, %s.", "%s, this conversation can serve no purpose anymore. Goodbye."]
end

app/models/pub_sub.rb
require 'net/http'
require 'uri'

class PubSub
  # These URI patterns must match those in the relevant Nginx config
  PUBLISH_URI   = '%s/push/publish?channel=%s'    
  SUBSCRIBE_URI = '%s/push/subscribe?channel=%s'

  # Returns Publish/Subscribe URI tuple with unique channel.
  # @param base_uri, a string, to build the pub and sub uris
  def self.pub_and_sub_uri(base_uri)
    channel = Time.now.strftime('%Y%m%d%H%M%S%L')
    [PUBLISH_URI % [base_uri, channel], SUBSCRIBE_URI % [base_uri, channel]]
  end
  
  attr_accessor :uri, :http

  # @param uri_string, the subscribe_uri from pub_and_sub_uri()
  def initialize(uri_string)
    @uri = URI.parse(uri_string)
    @http = Net::HTTP.new(uri.host, uri.port)
  end

  # Publish data in JSON format.
  # @param message, a string
  # @option error, a boolean, default false
  # @option eot, a boolean, true if end-of-transmission, default false
  def publish(message, options = {})
    error   = options[:error] || false
    eot     = options[:eot]   || false
    request = Net::HTTP::Post.new(uri.request_uri)
    request.body = {
      :message => message, 
      :error   => error ? 1 : 0, 
      :eot     => eot   ? 1 : 0
    }.to_json
    request.content_type = 'text/json'
#   request['accept']    = 'text/json'
    http.request(request)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def delayed_job_admin_authentication
    true
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
  end

  def new
  end

  def create
    publish_uri, @subscribe_uri = PubSub.pub_and_sub_uri(request.url.gsub(request.fullpath, ''))
    Delayed::Job.enqueue Job.new(params[:name], publish_uri)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/create.html.erb
<h3><%= @subscribe_uri %></h3>

<div id="output">
  <ul id="messages"></ul>
  <div id="dismiss"><%= button_to 'ok', jobs_path, :method => :get %></div>
</div>

<script type="text/javascript">
  $(function() { 
    $('#dismiss').hide();
  });
  
  subscribe('<%= @subscribe_uri %>', function(message, error, eot) {
    var klass = error ? 'failure' : 'success';
    if (eot) {
      klass += ' eot';
      $('#dismiss').show();
    }
    $('#messages').append('<li class="' + klass + '" >' + message + '</li>');
  });
</script>

app/views/jobs/index.html.erb
<h1>Jobs</h1>
<%= link_to 'New Job', new_job_path %>

app/views/jobs/new.html.erb
<h1>New job</h1>
<%= form_tag(jobs_path) do |f| %>
  <div class="field">
    <label>Name</label><br />
    <%= text_field_tag :name, nil, :autocomplete => 'off' %>
  </div>
  <div class="actions">
    <%= submit_tag 'go' %>
  </div>
<% end %>
<%= link_to 'Back', jobs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HttpPush</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>